source "https://rubygems.org"

gem "fluentd"
gem "mysql2"
gem "activerecord"
gem "blather"
gem "aws-sdk-v1"
gem "xmpp4r"
gem "multi_xml"
gem "eventmachine"
gem "god"
gem "tlsmail"
gem "fluent-logger"
gem "fluent-plugin-s3"
gem "redis"
gem "rspec"
gem "process_safe_logger"
gem 'pry'
gem 'simplecov'